# Site settings
title: Travelog
subtitle: "Journal of Felix"
email: felixchiasson@domain.ca
description: "Make the footer happy by entering a short description about yourself here"
baseurl: 
url: "http://felixchiasson.github.io"
twitter_username: "faylics"
github_username:  "felixchiasson"
instagram_username: "felixchiasson"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
